[[press]]
title = "To Africa with Love"
source = "St. Louis American"
date = "March 26, 2009"
url = "/press/livingit.pdf"

[[press]]
title = "Arica for Mother's Day"
source = "St. Louis American"
date = "May 15, 2008"
url = "/press/mothersDay.pdf"


[[press]]
title = "The Fabrick of African Dance"
source = "St. Louis Post-Dispatch"
date = "February 1, 2007"
url = "/press/fabric.pdf"


[[press]]
title = "Dance Afrika with Afriky Lolo and Yele"
source = "St. Louis Post-Dispatch"
date = "January 26, 2006"
url = ""


[[press]]
title = "Movements with meaning: Ethnic dance is part workout, part celebration of the past"
source = "St. Louis Post-Dispatch"
date = "November 28, 2005"
url = "/press/Ethnic-dance.pdf"

[[press]]
title = "Dance for Joy"
source = "St. Louis Post-Dispatch"
date = "August 18, 2003"
url = ""


[[press]]
title = "UMSL’s African Cultures Lab Offers Students Memorable, Hands-On Insight Dancing and Music Brings History Alive"
source = "St. Louis Post-Dispatch"
date = "March 3, 1999"
url = "/press/african-cultures.pdf"
